#### TRYING TO REGISTER

POST http://localhost:1234/auth/register
Content-Type: application/json

{
  "firstName": "Umando",
  "lastName": "Ramirez Perez",
  "role": "vendedor",
  "email": "cecssis@gmail.com",
  "phoneNumber": "8095345541",
  "password": "12345678"
}

#### ACTIVATE ACCOUNT

POST http://localhost:1234/auth/activate
Content-Type: application/json

{
  "token": ""
}