#### TRYING TO REGISTER

POST http://localhost:1234/auth/register
Content-Type: application/json

{
  "firstName": "Gustavo",
  "lastName": "Paredes Perez",
  "role": "vendedor",
  "email": "manos@gmail.com",
  "phoneNumber": "8095345541",
  "password": "12345678"
}